version: '3'
services:
  planet:
    container_name: planet
    build: .
    image: planet
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=planet.fsfe.org,www.planet.fsfe.org
      - LETSENCRYPT_HOST=planet.fsfe.org,www.planet.fsfe.org
      - LETSENCRYPT_EMAIL=contact@fsfe.org

  # Connect the container which exposes the service to the 'bridge' network as
  # this is where the reverse proxy is
  connect-bridge:
    image: docker:dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - planet
    command: /bin/sh -c 'docker network connect bridge planet'
